version: '2.2'
services:
  mongo:
    image: mongo:3.4
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    networks:
      - unifi
    restart: always
    volumes:
      - /atlas/unifi/db:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: ${COMPOSE_PROJECT_NAME}_controller
    build: .
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - /atlas/unifi/data:/unifi/data
      - /atlas/unifi/log:/unifi/log
      - /atlas/unifi/cert:/unifi/cert
      - /atlas/unifi/init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      JVM_MAX_HEAP_SIZE: 1024M
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery

networks:
  unifi:
